### ISSUE TITLE
强烈建议将TEMPLATE文件夹的映射也一并写入docker的安装命令中

### ISSUE THREAD

**Issue by chenryace** [helloxz/docker-onenav#3]
### 我尝试安装时修改docker命令并映射default/template出来，但无法实现，容器直接跑不了。
然后只能通过docker instpect容器的方式找到具体的docker文件夹才能修改主题中的参数。希望你能采纳我的意见，这样大家都可以定制属于自己的主题，~~当然有些不会修改HTML文件的还是会不懂~~，但大家起码可以更方便去修改，**_也便于创造onenav的多样性_**。

**Comment by helloxz** [comment]
建议参考下这个文档：[Docker版更换主题](https://doc.xiaoz.me/books/onenav/page/0e659#bkmrk-docker%E7%89%88%E6%9B%B4%E6%8D%A2%E4%B8%BB%E9%A2%98)

**Comment by helloxz** [comment]
1. 在您的挂载目录下创建一个templates目录，然后将主题解压至此目录
2. 打开OneNav后台 - 系统设置 - 主题设置 - 选择要使用的主题

**Comment by helloxz** [comment]
OneNav的逻辑是优先查找`templates/`下的模板，如果未找到，然后查找`data/templates`下的模板，Docker是挂载了`data`目录的，所以你只需要在挂载目录下创建一个`templates`目录就行了。

**Comment by chenryace** [comment]
> OneNav的逻辑是优先查找`templates/`下的模板，如果未找到，然后查找`data/templates`下的模板，Docker是挂载了`data`目录的，所以你只需要在挂载目录下创建一个`templates`目录就行了。

哦，原来如此，等9.22更新的时候再搞

**Comment by helloxz** [comment]
`0.9.22`已经更新了。
